name: Report a Bug 🐞
description: Help us improve by reporting an issue.
title: "[BUG] Brief description"
labels: [ "status: awaiting triage" ]

body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Is this a new issue?
      description: Please confirm you've checked that this issue hasn't been reported before.
      options:
        - label: I have searched "open" and "closed" issues, and this is not a duplicate.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (if applicable)
      description: Attach screenshots to help explain your issue.
    validations:
      required: false

  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug! Please make sure to fill out all the sections to help us address the issue effectively.




  - type: markdown
    attributes:
      value: |
          Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
            label: Describe your issue
            placeholder: When I click here this happens
    validations:
            required: true
  - type: textarea
    id: steps
    attributes:
            label: Steps to reproduce
            placeholder: |
              1. Go to page X
              2. Click here
              3. Click there
    validations:
            required: true
  - type: textarea
    id: expected
    attributes:
            label: What was the expected result?
            placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
            label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: assign
    attributes:
            label: "Would you like to work on this issue?"
            options:
              - "Yes"
  - type: markdown
    attributes:
            value: |
              Thanks for reporting this issue! We will get back to you as soon as possible.