name: Feature Request
description: Have a new idea or feature? Let us know...
title: "[FEATURE] <brief description>"
labels: ["status: awaiting triage"]

body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Is this feature already requested?
      description: Ensure this feature hasn't been suggested before.
      options:
        - label: I have checked "open" and "closed" issues and this is not a duplicate.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Missing Functionality
      description: Briefly describe the problem or the missing functionality that this feature would address.
      placeholder: "Example: I'm frustrated when I can't [describe the issue]. This feature would help by [explain how]."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you're suggesting and how it would solve the problem. Include any relevant details or references.
      placeholder: "Example: I propose adding [describe feature] that would [explain how it solves the problem]. For reference, [mention any similar features in other projects]."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: Attach any screenshots that might help illustrate the feature or its need.
      placeholder: "Drag and drop images here or click to upload."
    validations:
      required: false

  - type: dropdown
    id: work_on_issue
    attributes:
      label: Would you like to work on this feature?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan (Optional)
      description: If you selected "Yes" above, briefly describe how you plan to implement this feature.
      placeholder: "Example: I plan to start by [outline steps], and I will use [mention any tools, libraries, or code]."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please ensure you've filled out all the required sections to help us evaluate your suggestion effectively.
